version: '3'
services:
    api:
        container_name: api
        build: .
        ports:
            - "3000:3000"
        volumes:
            - ./api:/var/www/api/
            - ./package.json:/var/www/package.json
        command: npm start

