version: '3'
services:
  lint:
    container_name: lint
    build: .
    volumes:
      - ./Api:/var/www/Api/
      - ./package.json:/var/www/package.json
      - ./.eslintrc.js:/var/www/.eslintrc.js
    command: npm run lint
